FROM mcr.microsoft.com/dotnet/runtime:6.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["MyGame/MyGame.csproj", "MyGame/"]
RUN dotnet restore "MyGame/MyGame.csproj"
COPY . .
WORKDIR "/src/MyGame"
RUN dotnet build "MyGame.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "MyGame.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "MyGame.dll"]
